domain: simtex-dev.github.io
url: https://simtex-dev.github.io
baseurl: /simtex-dev.github.io/

theme: minima

title: "Simtex"
layout: page
description: Convert your files into LaTeX/pdf with one command!

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

github_username: simtex-dev
