domain: simtex-dev.github.io
url: https://simtex-dev.github.io
baseurl: /simtex-dev.github.io/

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Simtex
description: Convert your files into LaTeX/pdf with one command!
